# Generated by Django 3.1.5 on 2021-02-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
