# Generated by Django 3.1.5 on 2021-02-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_auto_20210210_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='email',
            field=models.EmailField(blank=True, max_length=180, null=True),
        ),
    ]
