# Generated by Django 3.1.5 on 2021-02-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id_coments', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('coment_text', models.TextField(max_length=2021)),
                ('date_of_coment', models.DateTimeField()),
                ('number_likes', models.IntegerField(max_length=12)),
            ],
            options={
                'ordering': ['date_of_coment'],
            },
        ),
    ]
