# Generated by Django 3.1.6 on 2021-02-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Histories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histories',
            name='history',
            field=models.ImageField(blank=True, null=True, upload_to='history'),
        ),
    ]
