# Generated by Django 3.1.6 on 2021-02-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=222)),
                ('email', models.EmailField(max_length=180)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id_followers', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('my_follows', models.IntegerField()),
                ('my_followers', models.IntegerField()),
                ('username', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='Cuentas.user')),
            ],
            options={
                'ordering': ['id_followers'],
            },
        ),
    ]
