# Generated by Django 3.1.5 on 2021-02-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('profile', models.ImageField(null=True, upload_to='profile')),
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=222)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('tlfn', models.CharField(max_length=12, null=True)),
                ('biography', models.TextField(blank=True, max_length=1200, null=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatText', models.TextField(max_length=2021)),
                ('date', models.DateTimeField()),
                ('username', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='Cuentas.cuentas')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
