# Generated by Django 3.1.5 on 2021-02-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0003_auto_20210210_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id_followers', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('my_follows', models.IntegerField(max_length=12)),
                ('my_followers', models.IntegerField(max_length=12)),
            ],
            options={
                'ordering': ['id_followers'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=222)),
                ('email', models.EmailField(max_length=180)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
