# Generated by Django 3.1.5 on 2021-02-18 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0004_auto_20210218_0138'),
        ('Posts', '0004_auto_20210218_0138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuentas',
        ),
        migrations.AddField(
            model_name='followers',
            name='username',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='Cuentas.user'),
        ),
    ]
