# Generated by Django 3.1.6 on 2021-02-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coments', '0001_initial'),
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id_posts', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('number_posts', models.IntegerField()),
                ('number_likes', models.IntegerField()),
                ('photo', models.ImageField(upload_to='posts')),
                ('description', models.TextField(max_length=500, null=True)),
                ('post_date', models.DateTimeField()),
                ('public_or_private', models.BooleanField()),
                ('id_coments', models.ForeignKey(max_length=80, on_delete=django.db.models.deletion.CASCADE, to='Coments.coments')),
                ('username', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='Cuentas.user')),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
    ]
