# Generated by Django 3.1.5 on 2021-02-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coments', '0001_initial'),
        ('Posts', '0002_auto_20210222_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id_coments',
            field=models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coments.coments'),
        ),
    ]
