# Generated by Django 3.1.5 on 2021-02-18 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0004_auto_20210218_0138'),
        ('Coments', '0001_initial'),
        ('Posts', '0003_auto_20210211_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id_posts', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('number_posts', models.IntegerField(max_length=12)),
                ('number_likes', models.IntegerField(max_length=12)),
                ('photo', models.ImageField(upload_to='posts')),
                ('description', models.TextField(max_length=500, null=True)),
                ('post_date', models.DateTimeField()),
                ('public_or_private', models.BooleanField()),
                ('id_coments', models.ForeignKey(max_length=80, on_delete=django.db.models.deletion.CASCADE, to='Coments.coments')),
                ('username', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='Cuentas.user')),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
        migrations.RemoveField(
            model_name='foto',
            name='username',
        ),
        migrations.DeleteModel(
            name='Coments',
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
