# Generated by Django 3.1.5 on 2021-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20210222_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='number_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
