# Generated by Django 3.1.5 on 2021-02-18 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuentas', '0004_auto_20210218_0138'),
        ('Posts', '0004_auto_20210218_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('biography', models.TextField(max_length=1000)),
                ('photo', models.ImageField(upload_to='profile')),
                ('id_followers', models.ForeignKey(max_length=80, on_delete=django.db.models.deletion.CASCADE, to='Cuentas.followers')),
                ('id_posts', models.ForeignKey(max_length=80, on_delete=django.db.models.deletion.CASCADE, to='Posts.posts')),
                ('username', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='Cuentas.user')),
            ],
            options={
                'ordering': ['id_profile'],
            },
        ),
    ]
