# Generated by Django 3.1.5 on 2021-02-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20210222_1647'),
        ('Cuentas', '0003_auto_20210219_0015'),
        ('Profile', '0002_auto_20210222_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_followers',
            field=models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cuentas.followers'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_posts',
            field=models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.posts'),
        ),
    ]
