# Generated by Django 3.1.6 on 2021-02-19 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0003_auto_20210219_0015'),
        ('Chat', '0002_auto_20210218_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Cuentas.user'),
        ),
    ]
