# Generated by Django 3.1.5 on 2021-02-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('foto', models.ImageField(upload_to='posts')),
                ('descripcion', models.TextField(max_length=500, null=True)),
                ('cat', models.CharField(max_length=12)),
                ('comment_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='Cuentas.cuentas')),
            ],
            options={
                'ordering': ['cat'],
            },
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('text', models.CharField(max_length=2021)),
                ('date', models.DateTimeField()),
                ('comment_code', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Posts.foto')),
                ('username', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='Cuentas.cuentas')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
