# Generated by Django 3.1.5 on 2021-02-11 03:32

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20210211_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='comment_code',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.fields.related.ManyToManyField, primary_key=True, serialize=False, to='Posts.foto'),
        ),
    ]
